CREATE TABLE IF NOT EXISTS task
(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    descriptions VARCHAR(200) NOT NULL,
    data TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE SEQUENCE IF NOT EXISTS task_id_seq START WITH 1 INCREMENT BY 1;